### PR TITLE
Add support to SRE Workbook.

### PR DESCRIPTION
**Pull request by aabouzaid**
These changes to make the scripts more generic to add support to [SRE Workbook](https://landing.google.com/sre/workbook/toc/).

Now we can generate books based on env variable.
e.g. to generate The Site Reliability Workbook (2018) book (after using image from this PR of course)
```
docker run --rm --volume "$(pwd):/output" -e BOOK_SLUG='srw_book' captn3m0/google-sre-ebook:latest
```

This fixes issue no. #19 

Thanks.

### CODE REVIEW

**Comment by kingdonb** [comment]
Awesome! You beat me to it, testing now

**Comment by kingdonb** [comment]
I found a lot of
```
Hyperlink target u'ch025.xhtml#level-of-sre-engagement-during-the-service-lifecycle' not found
Hyperlink target u'ch017.xhtml#ch11fn5' not found
Hyperlink target u'ch017.xhtml#ch11fn4' not found
Hyperlink target u'ch017.xhtml#ch11fn1' not found
Hyperlink target u'ch017.xhtml#ch11fn3' not found
Hyperlink target u'ch017.xhtml#ch11fn2' not found
Hyperlink target u'ch009.xhtml#practical-alerting' not found
Hyperlink target u'ch015.xhtml#service-fault' not found
Hyperlink target u'ch007.xhtml#slo-compliance-report' not found
Hyperlink target u'ch005.xhtml#id-e82c8uwuxc1' not found
```
messages in the output, for both books.  Not sure if this is a regression, but it seems that most of the links are still there and working, at least in the PDF format – I was able to generate all formats of both books from this branch.  I will play-test them today.  Thanks!

**Comment by kingdonb** [comment]
The updates are great!  Both books are showing up with images properly included in the pages now, on mobi format.  You have done a better job fixing this up than I was prepared to do.  I will see if I can find out more about the apparently broken links, but I only found working links while I was browsing through the content myself, so apparently if there are broken links, it's only some of them.

The irony is also not lost on me that I am reading Google's SRE books on Amazon's reader device, ha ha...

**Review by captn3m0 — APPROVED** [review]
:1st_place_medal:

**Comment by aabouzaid** [comment]
@kingdonb Thanks for your comments :-)

This problem happens with old version too.
Honestly I didn't look into it since no much effect on the result.

@captn3m0 Thanks for the merging :-)

**Comment by captn3m0** [comment]
Thanks a lot @AAbouZaid, this looks great :100: 

Now that we have both books covered, I've created an issue to track typesetting or other reading issues: #22 

Will take them up one by one, but feel free to add issues there.

**Pull request merged**
