### PR TITLE
Use absolute paths for epub generation

### PR DESCRIPTION
**Pull request by woneill**
I was getting ```OSError: [Errno 2] No such file or directory``` errors from `os.rename` without these changes.

Also updated the permissions on bootstap.sh

### CODE REVIEW

**Comment by captn3m0** [comment]
Thanks a lot. I'm adding you to the contributors on the repo, in case you want to help out further with the file generation (there is still a lot to be done)

**Comment by woneill** [comment]
Cool- appreciate that!

Yeah, once I noticed that entire chapters were missing from the ebook I generated I figured there was still lots to do :)

**Comment by captn3m0** [comment]
@woneill I realized I'm much better at this with ruby than python, and made a Ruby version (Default branch=`ruby`). It still has some issues (noted in README), but can you try out a first pass and see if looks readable to you?

**Comment by woneill** [comment]
Just took a look at your changes and realized that I'd need to ensure `pandoc` and `calibre` (to get `ebook-convert`) were installed. Fortunately I already had `calibre`!

Turns out I was able to get a decent book solely by running the retrieved HTML through ebook-convert:

```
wget --convert-links --mirror https://landing.google.com/sre/book/
cd landing.google.com/sre/book
ebook-convert index.html book.epub
ebook-convert index.html book.mobi
```

**Comment by captn3m0** [comment]
That sounds great!

I had to take care of internal links, chapter headers, and footnotes. Need to see if they are preserved properly in this version.

**Comment by captn3m0** [comment]
I tried running this, and lots of chapters in the EPUB seem empty. Was that the case for you as well?

**Pull request merged**
