### PR TITLE
Alpine image

### PR DESCRIPTION
**Pull request by mahmoudhossam**
This uses an Alpine Linux image to generate the book in EPUB format.

This is a partial solution to #16

### CODE REVIEW

**Comment by captn3m0** [comment]
@mahmoudhossam Can you give me commit rights on the branch? [[Doc](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/)]

**Comment by mahmoudhossam** [comment]
@captn3m0 Done.

Can you tell me what you'd like to change though?

**Comment by captn3m0** [comment]
- Add flags to `bootstrap.sh` to allow building partially. 
- Add documentation in README about split into 2 docker images and how to use them for generating specific versions (which one to use for what)

**Comment by mahmoudhossam** [comment]
@captn3m0 In that case, go ahead :+1:

**Comment by jethroguce** [comment]
👍

**Comment by captn3m0** [comment]
I've worked on this off and on, and its proven hard to setup and maintain. Closing.

Thanks for the contribution :+1:

**Pull request closed without merging**
